"""Initial migration

Revision ID: 2b4aa5b74e7f
Revises: 
Create Date: 2025-06-27 13:19:25.788997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4aa5b74e7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bureau_de_vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('centre_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_bureau_centre', 'centre_vote', ['centre_id'], ['id'])
        batch_op.drop_column('departement')
        batch_op.drop_column('commune')
        batch_op.drop_column('region')
        batch_op.drop_column('adresse')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bureau_de_vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adresse', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('region', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('commune', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('departement', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint('fk_bureau_centre', type_='foreignkey')
        batch_op.drop_column('centre_id')

    # ### end Alembic commands ###
