"""Add phone_number to User model

Revision ID: 2dab2fc57036
Revises: 0542159e00b6
Create Date: 2025-06-16 16:28:13.954516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dab2fc57036'
down_revision = '0542159e00b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=False))
        # batch_op.create_unique_constraint(None, ['phone_number'])
        batch_op.create_unique_constraint('uq_user_phone_number', ['phone_number'])

        # batch_op.drop_constraint('user_email_key', type_='unique')
        # batch_op.create_unique_constraint(None, ['email'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phone_number')
        # batch_op.create_unique_constraint('user_email_key', ['email'])
        # batch_op.drop_constraint(None, type_='unique')
       
