"""empty message

Revision ID: 504422604cb6
Revises: 3fcd1caf900c
Create Date: 2025-05-12 12:38:15.866572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504422604cb6'
down_revision = '3fcd1caf900c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('campaign_start_date')
        batch_op.drop_column('campaign_end_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_end_date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('campaign_start_date', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
